language: java
jdk:
  - oraclejdk7
env:
  global:
    - secure: "bqhaJSGeBvRhIYo7svJo0MFaasuRgQHGru6Z1JB0RzRvhwzq/v+tOy6s3PNkgpA/dWfMAAL7rByVF6zze4Mu4S4AHaF2FpZHCdvOhOdZSYle513NPvqcl6LGpZdjNxgedhD2OPnKIyOwIhDnI0YoBwdhK4leGZVRVxN8Nq4/cr0="
script:
  - touch file.test
  
  - git clone https://github.com/RhiobeT/testsTravis.git
  
  - cp --target-directory=testsTravis file.test
  
  - cd testsTravis  
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://${GH_TOKEN}:@github.com" > .git/credentials
  
  - git config user.email ${GIT_EMAIL}
  - git config user.name ${GIT_NAME}
  - git config push.default simple
  
  - git add file.test
  - git commit -m "[skip ci] Commit from Travis-CI"
  - git push