language: java

jdk:
  - oraclejdk7

env:
  global:
    - secure: "AIKcjNo07qRSdyB0bI144P3OL5Okmhh1BB0LUeN3mt4iXV3bdVQkOLod4vy/N2ho2vfwUO61xjrzUw6OZx0eeptECMtCVPWI2PRm+BnjAz1rQzIKq8Jo/Haffiv3EdZV9Q41mWlU3TVPPfS2p8RkUFkqFm1FXiNadIr4HKKiRPI="

install:
# update ubuntu repositories
  - sudo apt-get update
 
# install the needed softwares
  - gem install asciidoctor
  - sudo apt-get install pandoc
  - sudo apt-get install graphviz --fix-missing

script:
# save current directory
  - baseDir=$(pwd)



# include configuration file
  - chmod 777 $baseDir/travisConfig/config.sh
  - source $baseDir/travisConfig/config.sh


  
# configure the variables for Github
  - git config --global user.email ${GIT_EMAIL}
  - git config --global user.name ${GIT_NAME}
  - git config --global push.default simple
  
# move inside the directory containing the document to generate
  - cd $sourceDir
  
# generate plantUML diagrams (if any)
  - chmod 777 $baseDir/travisScripts/plantUML.sh
  - source $baseDir/travisScripts/plantUML.sh
    
# generate the html version of the document
  - htmlGenerationCommand

# generate the mediawiki version of the document
  - mediawikiGenerationCommand1
  - mediawikiGenerationCommand2
  


# compile the tests
  - cd $testsDir
  - compilationTests
  
# launch the tests
  - cd $sourceDir
  - lancementTests


  
# clone the "doc_release" branch in directory "_doc_release"
  - git clone -q $repository --branch $branch --single-branch $cloneDir

# move inside the _doc_release directory
  - cd $cloneDir

# set GitHub credentials
  - git config credential.helper "store --file=.git/credentials"
  - echo https://${GH_TOKEN}:@github.com > .git/credentials



after_success:
# copy files to commit
  - mkdir -p $successDir
  - cd $successDir
  - rm -R *
  - cd ..
  - cp --target-directory=$successDir -R $baseDir/srcdoc/images
  - cp --target-directory=$successDir -R $baseDir/srcdoc/stylesheet
  - cp --target-directory=$successDir $baseDir/srcdoc/*.html
  - cp --target-directory=$successDir $baseDir/srcdoc/*.mediawiki

# add files for commit
  - git add $successDir



after_failure:
# copy files to commit
  - mkdir -p $failureDir
  - cd $failureDir
  - rm -R *
  - cd ..
  - cp --target-directory=$failureDir -R $baseDir/srcdoc/images
  - cp --target-directory=$failureDir -R $baseDir/srcdoc/stylesheet
  - cp --target-directory=$failureDir $baseDir/srcdoc/*.html
  - cp --target-directory=$failureDir $baseDir/srcdoc/*.mediawiki

# add files for commit
  - git add $failureDir



after_script:
# commit and push on Github
  - git commit -m "[skip ci] Commit from Travis-CI"
  - git push -q